#!/bin/bash
cd ~/work
rm -rf android/build
rm -rf android/vendor/rising
git clone https://github.com/shravansayz/android_build.git android/build
git clone https://github.com/shravansayz/android_vendor_rising.git android/vendor/rising
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 100G
ccache -o compression=true
ccache -z
. build/envsetup.sh
lunch "$LUNCH_COMBO"
mka $TARGET -j8
